version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

auto-bump-groups:
  - group-name: "react-and-react-dom"
    update-types: ["patch"]
    include-paths:
      - "packages/ui/package.json"
    packages:
      - "react"
      - "react-dom"
